export const doctorSchemas = {
  DoctorStatus: {
    type: 'string',
    enum: ['ACTIVE', 'INACTIVE', 'ON_LEAVE', 'SUSPENDED', 'RETIRED'],
  },
  DayOfWeek: {
    type: 'string',
    enum: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'],
  },
  AppointmentMode: {
    type: 'string',
    enum: ['IN_PERSON', 'ONLINE', 'VIDEO', 'PHONE'],
  },
  ConsultationType: {
    type: 'string',
    enum: ['NEW', 'FOLLOW_UP', 'EMERGENCY'],
  },
  UpdateDoctorProfileRequest: {
    type: 'object',
    properties: {
      employeeId: { type: 'string' },
      registrationNumber: { type: 'string' },
      licenseNumber: { type: 'string' },
      experienceYears: { type: 'integer' },
      gender: { $ref: '#/components/schemas/Gender' },
      dateOfBirth: { type: 'string', format: 'date' },
      bloodGroup: { type: 'string' },
      bio: { type: 'string' },
      address: { type: 'string' },
      emergencyContactName: { type: 'string' },
      emergencyContactPhone: { type: 'string' },
      isAvailable: { type: 'boolean' },
      consultationDuration: { type: 'integer' },
      status: { $ref: '#/components/schemas/DoctorStatus' },
    },
  },
  ChamberRequest: {
    type: 'object',
    required: ['name'],
    properties: {
      name: { type: 'string' },
      roomNumber: { type: 'string' },
      floor: { type: 'string' },
      branchName: { type: 'string' },
      address: { type: 'string' },
      isPrimary: { type: 'boolean' },
      isActive: { type: 'boolean' },
    },
  },
  ScheduleRequest: {
    type: 'object',
    required: ['dayOfWeek', 'startTime', 'endTime'],
    properties: {
      chamberId: { type: 'string', format: 'uuid' },
      dayOfWeek: { $ref: '#/components/schemas/DayOfWeek' },
      startTime: { type: 'string', example: '09:00' },
      endTime: { type: 'string', example: '13:00' },
      maxPatients: { type: 'integer' },
      slotDuration: { type: 'integer' },
      appointmentMode: { $ref: '#/components/schemas/AppointmentMode' },
      isActive: { type: 'boolean' },
    },
  },
  FeeConfigRequest: {
    type: 'object',
    required: ['appointmentMode', 'consultationType', 'amount'],
    properties: {
      id: { type: 'string', format: 'uuid' },
      chamberId: { type: 'string', format: 'uuid' },
      appointmentMode: { $ref: '#/components/schemas/AppointmentMode' },
      consultationType: { $ref: '#/components/schemas/ConsultationType' },
      amount: { type: 'number' },
      currency: { type: 'string', default: 'BDT' },
      isActive: { type: 'boolean' },
    },
  },
  LeaveRequest: {
    type: 'object',
    required: ['startDate', 'endDate'],
    properties: {
      startDate: { type: 'string', format: 'date' },
      endDate: { type: 'string', format: 'date' },
      reason: { type: 'string' },
      isFullDay: { type: 'boolean' },
    },
  },
  Doctor: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      tenantId: { type: 'string', format: 'uuid' },
      userId: { type: 'string', format: 'uuid' },
      employeeId: { type: 'string', nullable: true },
      registrationNumber: { type: 'string', nullable: true },
      licenseNumber: { type: 'string', nullable: true },
      experienceYears: { type: 'integer', nullable: true },
      gender: { $ref: '#/components/schemas/Gender', nullable: true },
      dateOfBirth: { type: 'string', format: 'date-time', nullable: true },
      bloodGroup: { type: 'string', nullable: true },
      bio: { type: 'string', nullable: true },
      address: { type: 'string', nullable: true },
      emergencyContactName: { type: 'string', nullable: true },
      emergencyContactPhone: { type: 'string', nullable: true },
      joiningDate: { type: 'string', format: 'date-time', nullable: true },
      isAvailable: { type: 'boolean' },
      consultationDuration: { type: 'integer' },
      status: { $ref: '#/components/schemas/DoctorStatus' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },
  Chamber: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      doctorId: { type: 'string', format: 'uuid' },
      name: { type: 'string' },
      roomNumber: { type: 'string', nullable: true },
      floor: { type: 'string', nullable: true },
      branchName: { type: 'string', nullable: true },
      address: { type: 'string', nullable: true },
      isPrimary: { type: 'boolean' },
      isActive: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },
  Schedule: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      doctorId: { type: 'string', format: 'uuid' },
      chamberId: { type: 'string', format: 'uuid', nullable: true },
      dayOfWeek: { $ref: '#/components/schemas/DayOfWeek' },
      startTime: { type: 'string' },
      endTime: { type: 'string' },
      maxPatients: { type: 'integer', nullable: true },
      slotDuration: { type: 'integer', nullable: true },
      appointmentMode: { $ref: '#/components/schemas/AppointmentMode' },
      isActive: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },
  FeeConfig: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      doctorId: { type: 'string', format: 'uuid' },
      chamberId: { type: 'string', format: 'uuid', nullable: true },
      appointmentMode: { $ref: '#/components/schemas/AppointmentMode' },
      consultationType: { $ref: '#/components/schemas/ConsultationType' },
      amount: { type: 'number' },
      currency: { type: 'string' },
      isActive: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },
  Leave: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      doctorId: { type: 'string', format: 'uuid' },
      startDate: { type: 'string', format: 'date-time' },
      endDate: { type: 'string', format: 'date-time' },
      reason: { type: 'string', nullable: true },
      isFullDay: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },
  DoctorSingleResponse: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: true },
      message: { type: 'string' },
      data: { $ref: '#/components/schemas/Doctor' },
    },
  },
  DoctorListResponse: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: true },
      message: { type: 'string' },
      data: {
        type: 'array',
        items: { $ref: '#/components/schemas/Doctor' },
      },
      meta: { $ref: '#/components/schemas/PaginationMeta' },
    },
  },
  ChamberListResponse: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: true },
      message: { type: 'string' },
      data: {
        type: 'array',
        items: { $ref: '#/components/schemas/Chamber' },
      },
    },
  },
  ScheduleListResponse: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: true },
      message: { type: 'string' },
      data: {
        type: 'array',
        items: { $ref: '#/components/schemas/Schedule' },
      },
    },
  },
  FeeConfigListResponse: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: true },
      message: { type: 'string' },
      data: {
        type: 'array',
        items: { $ref: '#/components/schemas/FeeConfig' },
      },
    },
  },
  LeaveListResponse: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: true },
      message: { type: 'string' },
      data: {
        type: 'array',
        items: { $ref: '#/components/schemas/Leave' },
      },
    },
  },
};
