export const patientSchemas = {
  Gender: {
    type: 'string',
    enum: ['MALE', 'FEMALE', 'OTHER'],
  },
  PatientStatus: {
    type: 'string',
    enum: ['ACTIVE', 'INACTIVE'],
  },
  CreatePatientRequest: {
    type: 'object',
    required: ['name', 'phone'],
    properties: {
      name: { type: 'string', example: 'Jannatul Ferdous' },
      phone: { type: 'string', example: '+8801712345678' },
      email: { type: 'string', format: 'email', nullable: true },
      age: { type: 'integer', minimum: 0, maximum: 150, nullable: true },
      dateOfBirth: { type: 'string', format: 'date-time', nullable: true },
      gender: { $ref: '#/components/schemas/Gender' },
      address: { type: 'string', nullable: true },
      bloodGroup: { type: 'string', maxLength: 10, nullable: true, example: 'A+' },
      maritalStatus: { type: 'string', maxLength: 50, nullable: true, example: 'Married' },
      occupation: { type: 'string', maxLength: 100, nullable: true, example: 'Teacher' },
      photoUrl: { type: 'string', format: 'uri', nullable: true },
      status: { $ref: '#/components/schemas/PatientStatus' },
      isActive: { type: 'boolean', nullable: true },
      notes: { type: 'string', nullable: true },
      tenantId: { type: 'string', format: 'uuid', nullable: true },
    },
  },
  UpdatePatientRequest: {
    type: 'object',
    minProperties: 1,
    properties: {
      name: { type: 'string', example: 'Jannatul Ferdous' },
      phone: { type: 'string', example: '+8801712345678' },
      email: { type: 'string', format: 'email', nullable: true },
      age: { type: 'integer', minimum: 0, maximum: 150, nullable: true },
      dateOfBirth: { type: 'string', format: 'date-time', nullable: true },
      gender: { $ref: '#/components/schemas/Gender' },
      address: { type: 'string', nullable: true },
      bloodGroup: { type: 'string', maxLength: 10, nullable: true, example: 'A+' },
      maritalStatus: { type: 'string', maxLength: 50, nullable: true, example: 'Married' },
      occupation: { type: 'string', maxLength: 100, nullable: true, example: 'Teacher' },
      photoUrl: { type: 'string', format: 'uri', nullable: true },
      status: { $ref: '#/components/schemas/PatientStatus' },
      isActive: { type: 'boolean', nullable: true },
      notes: { type: 'string', nullable: true },
      tenantId: { type: 'string', format: 'uuid', nullable: true },
    },
  },
  PatientAddress: {
    type: 'object',
    additionalProperties: true,
    properties: {
      id: { type: 'string', format: 'uuid' },
      patientId: { type: 'string', format: 'uuid' },
      type: { type: 'string', example: 'HOME' },
      addressLine: { type: 'string', example: 'Dhaka, Bangladesh' },
      isPrimary: { type: 'boolean', example: true },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },
  Patient: {
    type: 'object',
    additionalProperties: true,
    properties: {
      id: { type: 'string', format: 'uuid' },
      tenantId: { type: 'string', format: 'uuid' },
      patientCode: { type: 'string', example: 'PAT-1712579020123-321' },
      firstName: { type: 'string', example: 'Jannatul' },
      lastName: { type: 'string', nullable: true, example: 'Ferdous' },
      phone: { type: 'string', example: '+8801712345678' },
      email: { type: 'string', format: 'email', nullable: true },
      dateOfBirth: { type: 'string', format: 'date-time', nullable: true },
      gender: { $ref: '#/components/schemas/Gender' },
      bloodGroup: { type: 'string', nullable: true, example: 'A+' },
      maritalStatus: { type: 'string', nullable: true, example: 'Married' },
      occupation: { type: 'string', nullable: true, example: 'Teacher' },
      photoUrl: { type: 'string', format: 'uri', nullable: true },
      status: { $ref: '#/components/schemas/PatientStatus' },
      isActive: { type: 'boolean', example: true },
      notes: { type: 'string', nullable: true },
      deletedAt: { type: 'string', format: 'date-time', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
      addresses: {
        type: 'array',
        items: { $ref: '#/components/schemas/PatientAddress' },
      },
    },
  },
  PaginationMeta: {
    type: 'object',
    properties: {
      page: { type: 'integer', example: 1 },
      limit: { type: 'integer', example: 10 },
      total: { type: 'integer', example: 34 },
      totalPages: { type: 'integer', example: 4 },
    },
  },
  PatientSingleResponse: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: true },
      message: { type: 'string', example: 'Patient retrieved successfully' },
      data: { $ref: '#/components/schemas/Patient' },
      meta: { type: 'object', nullable: true, additionalProperties: true },
    },
  },
  PatientListResponse: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: true },
      message: { type: 'string', example: 'Patients retrieved successfully' },
      data: {
        type: 'array',
        items: { $ref: '#/components/schemas/Patient' },
      },
      meta: { $ref: '#/components/schemas/PaginationMeta' },
    },
  },
};
