export const prescriptionSchemas = {
  PrescriptionStatus: {
    type: 'string',
    enum: ['DRAFT', 'ISSUED', 'CANCELLED', 'COMPLETED'],
  },
  PrescriptionItem: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      medicineName: { type: 'string' },
      genericName: { type: 'string', nullable: true },
      dosage: { type: 'string', nullable: true },
      frequency: { type: 'string', nullable: true },
      durationValue: { type: 'integer', nullable: true },
      durationUnit: { type: 'string', nullable: true },
      route: { type: 'string', nullable: true },
      instruction: { type: 'string', nullable: true },
      quantity: { type: 'string', nullable: true },
      timing: { type: 'string', nullable: true },
      sortOrder: { type: 'integer' },
      metadata: { type: 'object', nullable: true },
    },
  },
  Prescription: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      tenantId: { type: 'string', format: 'uuid' },
      patientId: { type: 'string', format: 'uuid' },
      doctorId: { type: 'string', format: 'uuid' },
      visitId: { type: 'string', format: 'uuid', nullable: true },
      prescriptionNumber: { type: 'string' },
      status: { $ref: '#/components/schemas/PrescriptionStatus' },
      diagnosis: { type: 'string', nullable: true },
      symptoms: { type: 'string', nullable: true },
      advice: { type: 'string', nullable: true },
      notes: { type: 'string', nullable: true },
      followUpDate: { type: 'string', format: 'date-time', nullable: true },
      issuedAt: { type: 'string', format: 'date-time', nullable: true },
      expiresAt: { type: 'string', format: 'date-time', nullable: true },
      metadata: { type: 'object', nullable: true },
      items: {
        type: 'array',
        items: { $ref: '#/components/schemas/PrescriptionItem' },
      },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },
  PrescriptionItemRequest: {
    type: 'object',
    required: ['medicineName'],
    properties: {
      medicineName: { type: 'string' },
      genericName: { type: 'string' },
      dosage: { type: 'string' },
      frequency: { type: 'string' },
      durationValue: { type: 'integer' },
      durationUnit: { type: 'string' },
      route: { type: 'string' },
      instruction: { type: 'string' },
      quantity: { type: 'string' },
      timing: { type: 'string' },
      sortOrder: { type: 'integer' },
      metadata: { type: 'object' },
    },
  },
  CreatePrescriptionRequest: {
    type: 'object',
    required: ['items'],
    properties: {
      doctorId: { type: 'string', format: 'uuid' },
      visitId: { type: 'string', format: 'uuid' },
      prescriptionNumber: { type: 'string' },
      status: { $ref: '#/components/schemas/PrescriptionStatus' },
      diagnosis: { type: 'string' },
      symptoms: { type: 'string' },
      advice: { type: 'string' },
      notes: { type: 'string' },
      followUpDate: { type: 'string', format: 'date-time' },
      issuedAt: { type: 'string', format: 'date-time' },
      expiresAt: { type: 'string', format: 'date-time' },
      metadata: { type: 'object' },
      items: {
        type: 'array',
        items: { $ref: '#/components/schemas/PrescriptionItemRequest' },
      },
    },
  },
  UpdatePrescriptionRequest: {
    type: 'object',
    properties: {
      status: { $ref: '#/components/schemas/PrescriptionStatus' },
      diagnosis: { type: 'string' },
      symptoms: { type: 'string' },
      advice: { type: 'string' },
      notes: { type: 'string' },
      followUpDate: { type: 'string', format: 'date-time' },
      issuedAt: { type: 'string', format: 'date-time' },
      expiresAt: { type: 'string', format: 'date-time' },
      metadata: { type: 'object' },
      items: {
        type: 'array',
        items: { $ref: '#/components/schemas/PrescriptionItemRequest' },
      },
    },
  },
  PrescriptionSingleResponse: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: true },
      message: { type: 'string' },
      data: { $ref: '#/components/schemas/Prescription' },
    },
  },
  PrescriptionListResponse: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: true },
      message: { type: 'string' },
      data: {
        type: 'array',
        items: { $ref: '#/components/schemas/Prescription' },
      },
      meta: { $ref: '#/components/schemas/PaginationMeta' },
    },
  },
};
